CREATE TABLE IF NOT EXISTS public.product
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255),
    price numeric(19,2) NOT NULL,

    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.market
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255),
    opening_time timestamp without time zone NOT NULL,
    closing_time timestamp without time zone NOT NULL,
    phone_number character varying(15),
    mobile_number character varying(16),

    CONSTRAINT market_pkey PRIMARY KEY (id)
);